spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/discount_service_development
    user: postgres
    password: postgres

  datasource:
    name: discountDev
    url: jdbc:postgresql://localhost:5432/discount_service_development
    username: postgres
    password: postgres
    maximum-pool-size: 10

server:
  port: 8080

dev:
  port: 10082